work on secure migration uploader

diff --git a/bin/upload-secure-migration b/bin/upload-secure-migration
--- a/bin/upload-secure-migration
+++ b/bin/upload-secure-migration
@@ -16,7 +16,8 @@ readonly aws_bucket_suffix="-us-west-2"
 readonly usage="usage: $0 <production_migration_file>"
 
 function proceed() {
-  echo -n "Proceed? (y/N) "
+  proceed_message=${1:-"proceed"}
+  echo -n "${proceed_message} (y/N) "
   read -r proceed
   if [[ "$proceed" =~ ^[^yY]*$ ]]; then
     echo "exiting"
@@ -28,6 +29,15 @@ function proceed() {
 # Pre-flight checks
 #
 
+if [[ -z "${1:-}" ]]; then
+  echo "$usage"
+  exit 1
+elif [[ ! -f "${1}" ]]; then
+  echo "error: unable to find migration file: ${1}"
+  exit 1
+fi
+readonly production_migration_file="$1"
+
 command -v "$aws" 2> /dev/null | grep "ppp-infra/bin/aws" &> /dev/null || \
   ( echo "error: aws command not pointing to 'ppp-infra/bin/aws";
     echo "see https://github.com/transcom/ppp-infra/blob/master/transcom-ppp/README.md#using-aws-vault";
@@ -35,7 +45,7 @@ command -v "$aws" 2> /dev/null | grep "ppp-infra/bin/aws" &> /dev/null || \
   )
 
 #
-# Freshen AWS token
+# Test AWS command and freshen AWS session token
 #
 
 aws s3 ls "${aws_bucket_prefix}${environments[0]}${aws_bucket_suffix}" > /dev/null
@@ -45,7 +55,7 @@ aws s3 ls "${aws_bucket_prefix}${environments[0]}${aws_bucket_suffix}" > /dev/nu
 #
 
 echo "Testing local migration. This will involve resetting your local dev database."
-proceed
+proceed "Proceed?"
 echo make db_dev_reset
 echo make db_dev_migrate
 
@@ -55,13 +65,15 @@ echo make db_dev_migrate
 
 for environment in "${environments[@]}"; do
   echo "Uploading to: $environment"
-  aws s3 cp ${
+  aws s3 cp --sse AES265 \
+    "$production_migration_file" \
+    s3://"${aws_bucket_prefix}${environment}${aws_bucket_suffix}"
 done
 
 #
 # Cleanup
 #
 
-for environment in "${environments[@]}"; do
-  echo "Uploading to: $environment"
-done
+echo "Production migration files contain sensitive data and should be deleted after uploading."
+proceed "Delete it now?"
+rm -v "$production_migration_file"
