fixing database connectivity test

diff --git a/bin/wait-for-db b/bin/wait-for-db
--- a/bin/wait-for-db
+++ b/bin/wait-for-db
@@ -3,7 +3,7 @@
 # reached. Useful to test database connectivity, or wait for local Docker
 # instances to spin up.
 
-set -eux -o pipefail
+set -eu -o pipefail
 
 db_password="${DB_PASSWORD:-mysecretpassword}"
 db_host="${DB_HOST:-localhost}"
@@ -11,13 +11,19 @@ db_user="${DB_USER:-postgres}"
 db_name="${DB_NAME:-postgres}"
 retries=0
 timeout=5
-db_check_command="psql postgres://${db_user}:${db_password}@${db_host}/${db_name} -c 'select 1;' &> /dev/null"
+db_check_command="psql postgres://${db_user}:${db_password}@${db_host}/${db_name} -c 'select 1;' > /dev/null"
+
+echo "> ${db_check_command}"
+echo -n "Checking for database connectivity.."
 
 while ! bash -c "$db_check_command"; do
   retries=$(( retries + 1 ))
   echo -n "."
   if [[ $retries -eq $timeout ]]; then
+    echo "failed!"
     exit 1
   fi
   sleep 1
 done
+
+echo "success!"
