try failed test check

diff --git a/scripts/check-failed-test b/scripts/check-failed-test
--- a/scripts/check-failed-test
+++ b/scripts/check-failed-test
@@ -1,16 +1,22 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
-if [ -z $1 ]; then
+#
+# Script to check xml for failed tests
+#
+
+set -eu -o pipefail
+
+if [ -z "$1" ]; then
   echo "Usage: $0 [path/to/file.xml]"
   exit 1
 fi
 
-if ! test -f $1; then
+if ! test -f "$1"; then
   echo "FILE NOT FOUND: $1"
   exit 1
 fi
 
-if grep "<failure" $1; then
+if grep "<failure" "$1"; then
   # Grep found line = error
   echo "LINT ERROR in $1"
   exit 1
