adjusted compare-deployed-commit code

diff --git a/scripts/compare-deployed-commit b/scripts/compare-deployed-commit
--- a/scripts/compare-deployed-commit
+++ b/scripts/compare-deployed-commit
@@ -47,12 +47,12 @@ else
   echo "* The deployed commit is either ahead of the local commit or the commits have different histories."
   echo "* Deploy is blocked."
 
+  # Ensure a status file is always written
   echo "failed" > sha_check_status
-  touch deploy_halt_flag  # This flag stops later jobs from running
 
 if [ -n "${GITLAB_CI+x}" ]; then
-  exit 0  # Prevents the job from failing but allows logical halting  
+  exit 0  # Prevents the job from failing but stops deployment
 else
-    exit 1
+  exit 1  # Fails locally if not running in GitLab
   fi
 fi
