Revert "Update download-secure-migration script for govcloud"
This reverts commit 9149cd57a269ba4db87dd31d58f1903815442acf.

This will be done by https://github.com/transcom/mymove/pull/4901

diff --git a/scripts/download-secure-migration b/scripts/download-secure-migration
--- a/scripts/download-secure-migration
+++ b/scripts/download-secure-migration
@@ -9,12 +9,9 @@ set -eu -o pipefail
 readonly aws_command="aws"
 # Environments to download production migrations from
 # shellcheck disable=SC2206
-readonly environments=(${ENVIRONMENTS:-exp stg prd})
-readonly valid_envs=("exp" "stg" "prd")
-readonly aws_gov_bucket_prefix="transcom-gov-milmove-"
-readonly aws_gov_bucket_suffix="-app-us-gov-west-1"
-readonly aws_gov_id_account="transcom-gov-id"
-readonly aws_gov_region="us-gov-west-1"
+readonly environments=(${ENVIRONMENTS:-experimental staging prod})
+readonly aws_bucket_prefix="transcom-ppp-app-"
+readonly aws_bucket_suffix="-us-west-2"
 readonly aws_path_prefix="secure-migrations"
 
 readonly usage="usage: $0 <production_migration_file>"
@@ -29,16 +26,15 @@ function proceed() {
   fi
 }
 
+function run() {
+  command=( "$@" )
+  echo "...executing: ${command[*]}"
+  ${command[*]} &> /dev/null || (echo "Failed!!" && exit 1)
+}
+
 #
 # Pre-flight checks
 #
-
-for environment in "${environments[@]}"; do
-  if [[ ! ${valid_envs[*]} =~ $environment ]]; then
-    echo "error: you submitted environment $environment. You may only pass in a subset of the following: ${valid_envs[*]}."
-    exit 1
-  fi
-done
 
 if [[ -z "${1:-}" ]]; then
   echo "$usage"
@@ -47,24 +43,7 @@ fi
 readonly production_migration_file="$1"
 
 # Test AWS command and freshen AWS session token
-for environment in "${environments[@]}"; do
-  if [[ $environment == "exp" ]]; then
-    readonly aws_gov_exp_account="${aws_gov_bucket_prefix}${environment}"
-    readonly aws_gov_exp_bucket_name="${aws_gov_exp_account}${aws_gov_bucket_suffix}"
-    DISABLE_AWS_VAULT_WRAPPER=1 AWS_PROFILE=${aws_gov_id_account} AWS_REGION=${aws_gov_region} aws-vault exec "${aws_gov_exp_account}" -- ${aws_command} s3 ls "${aws_gov_exp_bucket_name}" > /dev/null
-    echo "confirmed: you have access to ${aws_gov_exp_bucket_name} bucket via account ${aws_gov_id_account}"
-  elif [[ $environment == "stg" ]]; then
-    readonly aws_gov_stg_account="${aws_gov_bucket_prefix}${environment}"
-    readonly aws_gov_stg_bucket_name="${aws_gov_stg_account}${aws_gov_bucket_suffix}"
-    DISABLE_AWS_VAULT_WRAPPER=1 AWS_PROFILE=${aws_gov_id_account} AWS_REGION=${aws_gov_region} aws-vault exec "${aws_gov_stg_account}" -- ${aws_command} s3 ls "${aws_gov_stg_bucket_name}" > /dev/null
-    echo "confirmed: you have access to ${aws_gov_stg_bucket_name} bucket via account ${aws_gov_id_account}"
-  elif [[ $environment == "prd" ]]; then
-    readonly aws_gov_prd_account="${aws_gov_bucket_prefix}${environment}"
-    readonly aws_gov_prd_bucket_name="${aws_gov_prd_account}${aws_gov_bucket_suffix}"
-    DISABLE_AWS_VAULT_WRAPPER=1 AWS_PROFILE=${aws_gov_id_account} AWS_REGION=${aws_gov_region} aws-vault exec "${aws_gov_prd_account}" -- ${aws_command} s3 ls "${aws_gov_prd_bucket_name}" > /dev/null
-    echo "confirmed: you have access to ${aws_gov_prd_bucket_name} bucket via account ${aws_gov_id_account}"
-  fi
-done
+${aws_command} s3 ls "${aws_bucket_prefix}${environments[0]}${aws_bucket_suffix}" > /dev/null
 
 #
 # Download secure migration
@@ -72,34 +51,12 @@ done
 
 for environment in "${environments[@]}"; do
   echo "Downloading from: $environment"
+  sleep 1
   migration_dir="./tmp/secure_migrations/${environment}"
   mkdir -p "${migration_dir}"
-  sleep 1
-  if [[ $environment == "exp" ]]; then
-    DISABLE_AWS_VAULT_WRAPPER=1 \
-      AWS_PROFILE=${aws_gov_id_account} \
-      AWS_REGION=${aws_gov_region} \
-      aws-vault exec "${aws_gov_exp_account}" -- ${aws_command} s3 cp --sse AES256 \
-      "s3://${aws_gov_exp_bucket_name}/${aws_path_prefix}/${production_migration_file}" \
-      "${migration_dir}/$production_migration_file"
-    echo "confirmed: you ran a secure migration to ${aws_gov_exp_bucket_name} via ${aws_gov_id_account}"
-  elif [[ $environment == "stg" ]]; then
-    DISABLE_AWS_VAULT_WRAPPER=1 \
-       AWS_PROFILE=${aws_gov_id_account} \
-       AWS_REGION=${aws_gov_region} \
-       aws-vault exec "${aws_gov_stg_account}" -- ${aws_command} s3 cp --sse AES256 \
-       "s3://${aws_gov_stg_bucket_name}/${aws_path_prefix}/${production_migration_file}" \
-       "${migration_dir}/$production_migration_file"
-    echo "confirmed: you ran a secure migration to ${aws_gov_stg_bucket_name} via ${aws_gov_id_account}"
-  elif [[ $environment == "prd" ]]; then
-    DISABLE_AWS_VAULT_WRAPPER=1 \
-       AWS_PROFILE=${aws_gov_id_account} \
-       AWS_REGION=${aws_gov_region} \
-       aws-vault exec "${aws_gov_prd_account}" -- ${aws_command} s3 cp --sse AES256 \
-       "s3://${aws_gov_prd_bucket_name}/${aws_path_prefix}/${production_migration_file}" \
-       "${migration_dir}/$production_migration_file"
-    echo "confirmed: you ran a secure migration to ${aws_gov_prd_bucket_name} via ${aws_gov_id_account}"
-  fi
+  run aws s3 cp \
+    "s3://${aws_bucket_prefix}${environment}${aws_bucket_suffix}/${aws_path_prefix}/${production_migration_file}" \
+    "${migration_dir}/$production_migration_file"
 done
 
 echo
