Add template validation to make up for not doing pre-commit check

diff --git a/scripts/ecs-deploy-service-container b/scripts/ecs-deploy-service-container
--- a/scripts/ecs-deploy-service-container
+++ b/scripts/ecs-deploy-service-container
@@ -120,6 +120,13 @@ readonly container_definition_json
 # echo "===== END TASK DEF ===="
 # echo
 
+# Validate the template after it has been constructed
+if ! jq empty <<< "${container_definition_json}"; then
+  echo
+  echo "Invalid JSON produced from task definiton template ${template}!"
+  exit 1
+fi
+
 # create new task definition with the given image
 echo "* Registering new task definition"
 
diff --git a/scripts/ecs-run-app-migrations-container b/scripts/ecs-run-app-migrations-container
--- a/scripts/ecs-run-app-migrations-container
+++ b/scripts/ecs-run-app-migrations-container
@@ -80,6 +80,13 @@ readonly container_definition_json
 # echo "===== END TASK DEF ===="
 # echo
 
+# Validate the template after it has been constructed
+if ! jq empty <<< "${container_definition_json}"; then
+  echo
+  echo "Invalid JSON produced from task definiton template ${template}!"
+  exit 1
+fi
+
 # create new task definition with the given image
 echo "Create a new task definition for task family ${task_family}"
 task_definition_arn=$(aws ecs register-task-definition --network-mode awsvpc --task-role-arn "ecs-task-role-app-migration-$environment" --family "$task_family" --container-definitions "$container_definition_json" --requires-compatibilities FARGATE --execution-role-arn "ecs-task-execution-role-app-$environment" --cpu 256 --memory 512 --query 'taskDefinition.taskDefinitionArn' --output text)
