Update script and readme

diff --git a/scripts/lint-yaml-with-spectral b/scripts/lint-yaml-with-spectral
--- a/scripts/lint-yaml-with-spectral
+++ b/scripts/lint-yaml-with-spectral
@@ -1,25 +1,22 @@
 #! /usr/bin/env bash
 
 #
-# Find scripts missing int he readme
+# Run spectral linter on external APIs
 #
 
 set -eu -o pipefail
 
+# Check that the files exist
+for YAML in "$@"
+do
+  if [ ! -f "$YAML" ]
+  then
+    echo "File not found: $YAML"
+    exit 1
+  fi
+done
+
+# Lint them with spectral
 yarn spectral  -F error -r swagger/.spectral.yml lint "$@"
 exit $?
-
-# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-# readonly DIR
-
-# missing=false
-# for script in "${DIR}"/*; do
-#   name=$(basename "${script}")
-#   if grep -Fq "${name}" "${DIR}/README.md" ; then
-#     echo >> /dev/null
-#   elif [[ ${name} != "README.md" ]]; then
-#     echo "Missing from scripts/README.md: ${name}"
-#     missing=true
-#   fi
-# done
 
