Check for port 6006 free before running tests

diff --git a/scripts/run-storybook-tests b/scripts/run-storybook-tests
--- a/scripts/run-storybook-tests
+++ b/scripts/run-storybook-tests
@@ -6,19 +6,30 @@
 
 set -eu -o pipefail
 
-docker-compose -f docker-compose.storybook.yml build --pull
-docker-compose -f docker-compose.storybook.yml up storybook_tests
-container=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $1}')
-return_code=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $6}')
+# check for storybook port to be free, if not offer to kill it
+scripts/kill-process-on-port 6006
 
-echo "Clean .loki directory"
-rm -rf .loki
+# verify it's free now, if not we need to bail
+pid=$(lsof -t -sTCP:LISTEN -i :"6006") || true
 
-echo "Copy results to .loki directory"
-docker cp "$container":/home/circleci/project/.loki/ .loki
-ls -lR .loki
+if [[ -z "$pid" ]]; then
+  docker-compose -f docker-compose.storybook.yml build --pull
+  docker-compose -f docker-compose.storybook.yml up storybook_tests
+  container=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $1}')
+  return_code=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $6}')
 
-echo "Shutdown containers"
-docker-compose -f docker-compose.storybook.yml down
+  echo "Clean .loki directory"
+  rm -rf .loki
 
-exit "$return_code"
+  echo "Copy results to .loki directory"
+  docker cp "$container":/home/circleci/project/.loki/ .loki
+  ls -lR .loki
+
+  echo "Shutdown containers"
+  docker-compose -f docker-compose.storybook.yml down
+
+  exit "$return_code"
+else
+  echo "port 6006 is taken cannot continue"
+  exit 1
+fi
