Update run-storybook-tests after merge

diff --git a/scripts/run-storybook-tests b/scripts/run-storybook-tests
--- a/scripts/run-storybook-tests
+++ b/scripts/run-storybook-tests
@@ -6,40 +6,7 @@
 
 set -eu -o pipefail
 
-if [[ -z ${CIRCLECI-} ]]; then
-  # not on CircleCI
-  # check for storybook port to be free, if not offer to kill it
-  scripts/kill-process-on-port 6006
-  # verify it's free now, if not we need to bail
-  pid=$(lsof -t -sTCP:LISTEN -i :"6006") || true
-
-  if [[ -z "$pid" ]]; then
-    docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml build --pull
-    docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml up storybook_tests
-    container=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $1}')
-    return_code=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $6}')
-
-    echo "Clean .loki directory"
-    rm -rf .loki
-
-    echo "Copy results to .loki directory"
-    docker cp "$container":/home/circleci/project/.loki/ .loki
-    ls -lR .loki
-
-    echo "Shutdown containers"
-    docker-compose -f docker-compose.storybook.yml down
-
-    exit "$return_code"
-  else
-    echo "port 6006 is taken cannot continue"
-    exit 1
-  fi
-else
-  # on CircleCI
-  # remove node_modules from dockerignore
-  sed -i='' '/^\/node_modules/d' .dockerignore
-  docker-compose -f docker-compose.storybook.yml build --pull
-  docker-compose -f docker-compose.storybook.yml up storybook_tests
+function run_tests() {
   container=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $1}')
   return_code=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $6}')
 
@@ -54,5 +21,30 @@ else
   docker-compose -f docker-compose.storybook.yml down
 
   exit "$return_code"
+}
+
+if [[ -z ${CIRCLECI-} ]]; then
+  # not on CircleCI
+  # verify port is free, if not we need to bail
+  # can't kill it since it maybe a docker container and that would kill Docker for Mac
+  pid=$(lsof -t -sTCP:LISTEN -i :"6006") || true
+
+  if [[ -z "$pid" ]]; then
+    docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml build --pull
+    docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml up storybook_tests
+
+    run_tests
+  else
+    echo "port 6006 is taken cannot continue, is storybook already running?"
+    exit 1
+  fi
+else
+  # on CircleCI
+  # remove node_modules from dockerignore
+  sed -i='' '/^\/node_modules/d' .dockerignore
+  docker-compose -f docker-compose.storybook.yml build --pull
+  docker-compose -f docker-compose.storybook.yml up storybook_tests
+
+  run_tests
 fi
 
